
import { type QuantumLevel } from '@/data/quantumLevels';

// This file is kept for backward compatibility but questions functionality has been removed
// Questions will be generated using AI instead of static content

export interface StoryQuestion {
  question: string;
  options: string[];
  correctAnswer: number;
  explanation: string;
}

export const getStoryQuestions = (levelId: number): StoryQuestion[] => {
  // Return empty array as questions are now generated by AI
  return [];
};

export const getStoryContent = (level: QuantumLevel): string => {
  const storyEnhancements: Record<number, string> = {
    1: "In the realm where classical and quantum worlds collide, you discover that reality itself can exist in multiple states. The ancient quantum masters speak of bits that can be both 0 and 1 simultaneously - a concept that challenges everything you thought you knew about information.",
    2: "Deep in the quantum realm, you encounter your first qubit - a mysterious entity that defies classical logic. Unlike the binary certainty of classical bits, this quantum warrior can dance between states, existing in a superposition that holds infinite possibilities until the moment of observation collapses it into reality.",
    3: "The quantum gates stand before you like ancient portals, each one capable of manipulating the very fabric of quantum reality. The Hadamard gate whispers secrets of superposition, while the Pauli gates offer the power to flip and rotate quantum states. Master these gates, and you master the building blocks of quantum computation.",
    4: "You enter the digital realm where images are composed of countless pixels, each holding color information in RGB channels. Here, classical image processing techniques await your mastery - filters that can enhance, blur, sharpen, and transform visual data through mathematical operations that reveal hidden patterns.",
    5: "In the algorithmic sanctum, you discover the legendary quantum algorithms that promise to revolutionize computation. Grover's algorithm offers the power to search through vast databases with quadratic speedup, while Shor's algorithm threatens to break the cryptographic foundations of the digital world.",
    6: "At the convergence of quantum computing and image processing, you find the cutting edge of technological evolution. Here, quantum states encode pixel information in ways that classical computers cannot fathom, promising exponential speedups for image analysis tasks through the mysterious power of quantum entanglement and superposition."
  };
  
  return storyEnhancements[level.id] || level.storyText;
};
