// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://khkzryoillbdvmwpsvhp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtoa3pyeW9pbGxiZHZtd3BzdmhwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NjY0OTgsImV4cCI6MjA2NTU0MjQ5OH0.XIIeNi-xO3uwd405P3Z7bZqFjGZxaLLoQYyy84Vi0o8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);